### PR TITLE
Fix crash on special characters input in expiry date

### LINKED ISSUE #259: App crash when trying input special character in ExpiryDateEditText
Hi team

I am facing crash issue when inputting asterisk (*) into ExpiryDateEditText, please help to check

Omise version: 4.8.0

Crash log:
`java.lang.NumberFormatException: For input string: "*"
	at java.lang.Integer.parseInt(Integer.java:604)
	at java.lang.Integer.parseInt(Integer.java:650)
	at co.omise.android.ui.ExpiryDateEditText.formatString(SourceFile:1)
	at co.omise.android.ui.ExpiryDateEditText.setExpiryDateText(SourceFile:3)
	at co.omise.android.ui.ExpiryDateEditText.access$setExpiryDateText(SourceFile:1)
	at co.omise.android.ui.ExpiryDateEditText$a.onTextChanged(SourceFile:15)
	at android.widget.TextView.sendOnTextChanged(TextView.java:10961)
	at android.widget.TextView.handleTextChanged(TextView.java:11076)
	at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:14205)
	at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:1268)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:577)
	at androidx.emoji2.text.SpannableBuilder.replace(SpannableBuilder.java:314)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:508)
	at androidx.emoji2.text.SpannableBuilder.replace(SpannableBuilder.java:304)
	at androidx.emoji2.text.SpannableBuilder.replace(SpannableBuilder.java:48)
	at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:944)
	at android.view.inputmethod.BaseInputConnection.commitText(BaseInputConnection.java:219)
	at com.android.internal.widget.EditableInputConnection.commitText(EditableInputConnection.java:204)
	at android.view.inputmethod.InputConnectionWrapper.commitText(InputConnectionWrapper.java:192)
	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:572)
	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:134)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:334)
	at android.app.ActivityThread.main(ActivityThread.java:8513)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)`

### PR DESCRIPTION
**Pull request by AnasNaouchi**
- Prevent input of special characters in the expiry date field for card payments.
- Changed input type to `InputType.TYPE_CLASS_NUMBER` to allow only numbers

Fixes #259

### CODE REVIEW

File: sdk/src/main/java/co/omise/android/ui/ExpiryDateEditText.kt [hunk 1]
```diff
@@ -73,6 +75,15 @@ class ExpiryDateEditText : OmiseEditText {
...
             if (s == null || s.length > MAX_CHARS) return
 
+            // Define a regular expression pattern to match non-numeric characters and DATE_SEPARATOR
+            val pattern: Pattern = Pattern.compile("[^0-9" + Pattern.quote(DATE_SEPARATOR) + "]")
+
+            // Use a Matcher to find any non-numeric characters in the string
+            val matcher: Matcher = pattern.matcher(s)
+            if(matcher.find()){
+                return
+            }
```
Comment (aashishgurung) [inline sdk/src/main/java/co/omise/android/ui/ExpiryDateEditText.kt:85]: Can we move this to a function? Maybe to a different class if this is useful in other parts of the code.

```
fun findAProperFunName(s: CharSequence?) {
    // Define a regular expression pattern to match non-numeric characters and DATE_SEPARATOR
    val pattern: Pattern = Pattern.compile("[^0-9" + Pattern.quote(DATE_SEPARATOR) + "]")

    // Use a Matcher to find any non-numeric characters in the string
    val matcher: Matcher = pattern.matcher(s)
    return matcher.find()
}

override fun onTextChanged(s: CharSequence?, start: Int, before: Int, count: Int) {
    if (s == null || s.length > MAX_CHARS) return

    if (findAProperFunName(s)) {
        return
    }

    // rest of the code
}
```

File: sdk/src/main/java/co/omise/android/ui/ExpiryDateEditText.kt [hunk 2]
```diff
@@ -73,6 +75,15 @@ class ExpiryDateEditText : OmiseEditText {
         override fun onTextChanged(s: CharSequence?, start: Int, before: Int, count: Int) {
             if (s == null || s.length > MAX_CHARS) return
 
+            // Define a regular expression pattern to match non-numeric characters and DATE_SEPARATOR
+            val pattern: Pattern = Pattern.compile("[^0-9" + Pattern.quote(DATE_SEPARATOR) + "]")
+
+            // Use a Matcher to find any non-numeric characters in the string
+            val matcher: Matcher = pattern.matcher(s)
+            if(matcher.find()){
```
Comment (danfowler) [inline sdk/src/main/java/co/omise/android/ui/ExpiryDateEditText.kt:83]: @AnasNaouchi do we have a way to enforce style here? I noticed a different spacing between `if` and the _expression_.

File: sdk/src/main/java/co/omise/android/ui/ExpiryDateEditText.kt (hunk 1 above)
Comment (aashishgurung) [reply sdk/src/main/java/co/omise/android/ui/ExpiryDateEditText.kt:85]: or maybe combine top two `if` statements.

```
    if (s == null || s.length > MAX_CHARS || findAProperFunName(s)) {
        return
    }
```

Comment (AnasNaouchi) [reply sdk/src/main/java/co/omise/android/ui/ExpiryDateEditText.kt:85]: > Can we move this to a function? Maybe to a different class if this is useful in other parts of the code.
> 
> ```
> fun findAProperFunName(s: CharSequence?) {
>     // Define a regular expression pattern to match non-numeric characters and DATE_SEPARATOR
>     val pattern: Pattern = Pattern.compile("[^0-9" + Pattern.quote(DATE_SEPARATOR) + "]")
> 
>     // Use a Matcher to find any non-numeric characters in the string
>     val matcher: Matcher = pattern.matcher(s)
>     return matcher.find()
> }
> 
> override fun onTextChanged(s: CharSequence?, start: Int, before: Int, count: Int) {
>     if (s == null || s.length > MAX_CHARS) return
> 
>     if (findAProperFunName(s)) {
>         return
>     }
> 
>     // rest of the code
> }
> ```

@aashishgurung  I would say to keep it as inline code directly as this is the pattern followed in the sdk currently and each text field validation is incapsulated in the class of the textfield itself (Maybe create a function in the class itslef). So date validations are within the date textfield class. Card validations are within the card text field class and so on. We do not have a centralized validation utility class. It's a nice to have I would say as doing that now will lead to a large refactor. Also these validations are kind of not totally reusable as Date validation is just for date validation and not anywhere else outside of the date class....

File: sdk/src/main/java/co/omise/android/ui/ExpiryDateEditText.kt (hunk 2 above)
Comment (AnasNaouchi) [reply sdk/src/main/java/co/omise/android/ui/ExpiryDateEditText.kt:83]: Yes we do have, you can format with android studio, for kotlin files. I was not enabled by default as it would result in some differences but will fix that

**Review by danfowler — DISMISSED** [review]

**Review by aashishgurung — DISMISSED** [review]

File: sdk/src/sharedTest/java/co/omise/android/ui/CreditCardActivityTest.kt [hunk 3]
```diff
@@ -102,7 +102,7 @@ class CreditCardActivityTest {
     fun form_validForm() {
         onView(withId(R.id.edit_card_number)).perform(typeText("4242424242424242"))
         onView(withId(R.id.edit_card_name)).perform(typeText("John Doe"))
-        onView(withId(R.id.edit_expiry_date)).perform(typeText("1234"))
+        onView(withId(R.id.edit_expiry_date)).perform(typeNumberText("1234"))
```
Comment (danfowler) [inline sdk/src/sharedTest/java/co/omise/android/ui/CreditCardActivityTest.kt:105]: @AnasNaouchi maybe one of the conditions we're not testing is `s.length > MAX_CHARS`

**Review by danfowler — APPROVED** [review]

**Review by aashishgurung — APPROVED** [review]
